version: '3.4'

services:
    postgres:
        container_name: app-mvc-basico-postgres
        image: postgres
        environment:
            POSTGRES_PASSWORD: "1234"
        ports:
            - "15432:5432"
        networks:
            - postgres-network
      
    pgadmin:
        container_name: app-mvc-basico-pgadmin
        image: dpage/pgadmin4    
        environment:
            PGADMIN_DEFAULT_EMAIL: "phillrog@hotmail.com"
            PGADMIN_DEFAULT_PASSWORD: "1234"
        ports:
            - "16543:80"
        depends_on:
            - postgres
        networks:
            - postgres-network

    appmvcbasico:
        container_name: app-mvc-basico-web
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=5004
        ports:
            - "4001:80"
            - "4004:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:
            - postgres
        networks:
            - postgres-network

networks: 
    postgres-network:
        driver: bridge