version: '3.4'

services:
    sql.database:
        container_name: app-mvc-basico-banco
        image: microsoft/mssql-server-linux:2017-latest
        environment:
            - SA_PASSWORD=123Aa321
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        networks:
            - mssql-network

    appmvcbasico:
        container_name: app-mvc-basico-web
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=4004
        ports:
            - "4001:80"
            - "4004:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:
            - sql.database
        networks:
            - mssql-network

networks: 
    mssql-network:
        driver: bridge