version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
        - "15432:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4    
    environment:
      PGADMIN_DEFAULT_EMAIL: "phillrog@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
        - "16543:80"
    depends_on:
        - postgres
    networks:
        - postgres-network

  web:
    container_name: app-mvc-baico
    build: 
      context: .
      dockerfile: ./AppMvcBasica/Dockerfile
    ports:
        - "5005:5000"
    networks:
        - postgres-network
    depends_on:
        - pgadmin

networks: 
  postgres-network:
    driver: bridge